MAX = 255
HALF = 127
MIN = 0

EMPTY = (MIN, MIN, MIN, MIN)

BLACK = (MIN, MIN, MIN)
GRAY = GREY = (HALF, HALF, HALF)
WHITE = (MAX, MAX, MAX)

RED  = (MAX, MIN, MIN)
LIME = (MIN, MAX, MIN)
BLUE = (MIN, MIN, MAX)

GREEN = (MIN, HALF, MIN)

YELLOW = (MAX, MAX, MIN)
PURPLE = (MAX, MIN, MAX)
CYAN   = (MIN, MAX, MAX)

ORANGE = (MAX, HALF, MIN)
PINK   = (MAX, 190, 203)

LIGHT_BLUE = (63, 63, MAX)
SKY_BLUE   = (63, 63, 200)

LIGHT_GRAY = LIGHT_GREY = (190, 190, 190)
DARK_GRAY = DARK_GREY  = (67, 67, 67)